### ISSUE TITLE
Content class - use byte[] instead of string?

### ISSUE THREAD

**Issue by justin-fyfe** [jembi/openmrs-module-shr-contenthandler#14]
I just noticed Content stores its payload as a String rather than just a series of bytes. Do you think that we should perhaps use just byte[] instead? Since the JAX classes represent attachments as byte[] and Everest will use a ByteArrayInputStream to consume the CDA :) ...

**Comment by rcrichton** [comment]
Fixed in f129b6b647926cad3ca0f0129f44cf60017a5909
